export default {
  'Opera': null,
  'Opera Coast': null,
  'SamsungBrowser': null,
  'NAVER Whale Browser': null,
  'MZ Browser': null,
  'Focus': null,
  'Swing': null,
  'Yandex Browser': null,
  'UC Browser': null,
  'Maxthon': null,
  'Epiphany': null,
  'Puffin': null,
  'Sleipnir': null,
  'K-Meleon': null,
  'Internet Explorer': null,
  'Microsoft Edge': null,
  'Vivaldi': null,
  'SeaMonkey': null,
  'Sailfish': null,
  'Amazon Silk': null,
  'PhantomJS': null,
  'SlimerJS': null,
  'BlackBerry': null,
  'WebOS Browser': null,
  'Bada': null,
  'Tizen': null,
  'QupZilla': null,
  'Firefox': null,
  'Chromium': null,
  'Chrome': null, // 'https://placehold.it/300x300',
  'Android Browser': null,
  'Safari': null,
  'Googlebot': null
};
